name: Release

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "docs"
      - ".vscode"

jobs:
  create-release:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Create a GitHub release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
